name: my_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.16.0
  firebase_messaging: ^11.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.5.0
  get: 4.6.1
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
